/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '25.11.15 13:36' with Gradle 2.7
 *
 * @author User, @date 25.11.15 13:36
 */

package org.gradle.testng;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
